global class BatchExample implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id,Name FROM Account';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Account> accList) {        
        for(Account acc : accList)
        {        
            acc.Name = acc.Name + '_Batch_Apex';
        }
        update accList; 
    }   
    global void finish(Database.BatchableContext BC) {
        System.debug('hey');
    }
}

/*BatchExample be = new BatchExample();
database.executeBatch(be,100);*/
